from tkinter import *
from tkinter import messagebox
import random
import time
import os
w=Tk()
w.geometry('1500x1500')
w.title("MY PIZZA")
canvas=Canvas(w,width=700,height=700)
canvas.place(x=900,y=98)
Tops=Frame(w,width=1500,height=50,relief=SUNKEN)
Tops.pack(side=TOP)
f1=Frame(w,width=1500,height=1000,relief=SUNKEN)
f1.pack(side=LEFT)
localtime=time.ctime()
lbl=Label(Tops,font=('ALGERIAN',38,'bold','underline'),text="MY PIZZA RESTAURANT",fg="navy blue",bd=10)
lbl.grid(row=0,column=0)
lbl=Label(Tops,font=('aerial bold',25,'bold','underline'),text=localtime,fg="purple",bd=10)
lbl.grid(row=1,column=0)
##############################################################
lbl=Label(Tops,font=('ALGERIAN',15,'bold','underline'),text="SHOP# 47 GULSHAN-E-IQBAL, KARACHI",fg="navy blue",bd=10)
lbl.grid(row=2,column=0)
##############################################################
def Ref():
    x=random.randint(10000,50000)
    randomRef=str(x)
    input.set(randomRef)
    costfries=int(fries.get())
    costfries1=int(fries1.get())
    costpizza1=int(pizza1.get())
    costpizza2=int(pizza2.get())
    costpizza3=int(pizza3.get())
    costdrink=int(drink.get())
    costdrink1=int(drink1.get())
    tcostfries=costfries*100
    tcostfries1=costfries1*200
    tcostpizza1=costpizza1*150
    tcostpizza2=costpizza2*300
    tcostpizza3=costpizza3*800
    tcostdrink=costdrink*110
    tcostdrink1=costdrink1*150
    costall=(tcostfries+tcostfries1+tcostpizza1+tcostpizza2+tcostpizza3+tcostdrink+tcostdrink1)
    tax=((tcostfries+tcostfries1+tcostpizza1+tcostpizza2+tcostpizza3+tcostdrink+tcostdrink1)*0.2)
    service=((tcostfries+tcostfries1+tcostpizza1+tcostpizza2+tcostpizza3+tcostdrink+tcostdrink1)*0.1)
    totalfinalbill=(tax+costall+service)
    servicecharges.set(service)
    taxcharges.set(tax)
    totalbill.set(totalfinalbill)
#####################################
def save():
    messagebox.showinfo("Bill Reciept","PAYMENT SUBMITTED THANK YOU PLEASE COLLECT YOUR ORDER AFTER 1 HOUR ")
############################################# IT WILL PRINT FINAL RESULTS ON CONSOLE WITH READING AND WRITING FILE################################################
    fr=str(fries.get())
    fr1=str(fries1.get())
    p1=str(pizza1.get())
    p2=str(pizza2.get())
    p3=str(pizza3.get())
    d=str(drink.get())
    d1=str(drink1.get())
    sc=servicecharges.get()
    tc=taxcharges.get()
    t=totalbill.get()
    print("YOUR BILL WITH ITEMS")
    print("drink",d1)
    print("fries 100",fr)
    print("fries 200",fr1)
    print("drink 2.25",d1)
    print("drink 1.5",d)
    print("service charges",sc)
    print("tax charges",tc)
    print("total bill",t)

    file = open("C:\\Users\\Hp\\Desktop\\pakk.txt","w")

    file.write(fr)
    file.write(fr1)
    file.write(p1)
    file.write(p2)
    file.write(p3)
    file.write(sc)
    file.write(tc)
    file.write(t)
    file.close()

####################################
def exit():
    w.destroy()
def reset():
    input.set("")
    fries.set("0")
    fries1.set("0")
    drink1.set("0")
    pizza1.set("0")
    pizza2.set("0")
    pizza3.set("0")
    drink.set("0")
    taxcharges.set("")
    servicecharges.set("")
    totalbill.set("")
    pizza4.set("0")
    pizza5.set("0")
    pizza6.set("0")
    pizza7.set("0")
    pizza8.set("0")
    var1.set("0")
    var2.set("0")
    var3.set("0")
    var4.set("0")
    var5.set("0")
input=StringVar()
fries=StringVar()
drink1=StringVar()
pizza1=StringVar()
pizza2=StringVar()
pizza3=StringVar()
pizza4=StringVar()
pizza5=StringVar()
pizza6=StringVar()
pizza7=StringVar()
pizza8=StringVar()
drink=StringVar()
fries1=StringVar()
taxcharges=StringVar()
servicecharges=StringVar()
totalbill=StringVar()
var1=StringVar()
var2=StringVar()
var3=StringVar()
var4=StringVar()
var5=StringVar()
lblreference=Label(f1,font=('aerial',16,'bold'),text="SPLIP NO",bd=10)
lblreference.grid(row=0,column=0)
txtreference=Entry(f1,font=("aerial",16,"bold"),textvariable=input,bd=10,insertwidth=4,bg="light green",justify="right")
txtreference.grid(row=0,column=1)
lblfries=Label(f1,font=('aerial',16,'bold'),text="FRIES RS-100",bd=10)
lblfries.grid(row=1,column=0)
txtfries=Entry(f1,font=("aerial",16,"bold"),textvariable=fries,bd=10,insertwidth=4,bg="orange",justify="right")
txtfries.grid(row=1,column=1)
lblfries1=Label(f1,font=('aerial',16,'bold'),text="FRIES RS-200",bd=10)
lblfries1.grid(row=2,column=0)
txtfries1=Entry(f1,font=("aerial",16,"bold"),textvariable=fries1,bd=10,insertwidth=4,bg="orange",justify="right")
txtfries1.grid(row=2,column=1)

lbldrink=Label(f1,font=('aerial',16,'bold'),text="DRINK 1.5LR",bd=10)
lbldrink.grid(row=3,column=0)
txtdrink=Entry(f1,font=("aerial",16,"bold"),textvariable=drink,bd=10,insertwidth=4,bg="orange",justify="right")
txtdrink.grid(row=3,column=1)
lbldrink1=Label(f1,font=('aerial',16,'bold'),text="DRINK 2.25LR",bd=10)
lbldrink1.grid(row=4,column=0)
txtdrink1=Entry(f1,font=("aerial",16,"bold"),textvariable=drink1,bd=10,insertwidth=4,bg="orange",justify="right")
txtdrink1.grid(row=4,column=1)
#######################################################

var11=Checkbutton(f1,text="CHIKEN FAJITA  ",variable=var1).grid(row=5,column=3)

var22=Checkbutton(f1,text="CHICKEN TIKKA  ",variable=var2).grid(row=6,column=3)

var33=Checkbutton(f1,text="CHEESY PIZZA   ",variable=var3).grid(row=7,column=3)


var44=Checkbutton(f1,text=" KABABISH PIZZA",variable=var4).grid(row=8,column=3)

var55=Checkbutton(f1,text=" CHICK AFGHANI",variable=var5).grid(row=9,column=3)
###########################################################
txt1=Entry(f1,font=("aerial",16,"bold"),textvariable=pizza4,bd=10,insertwidth=4,bg="orange",justify="right")
txt1.grid(row=5,column=4)
txt2=Entry(f1,font=("aerial",16,"bold"),textvariable=pizza5,bd=10,insertwidth=4,bg="orange",justify="right")
txt2.grid(row=6,column=4)
txt3=Entry(f1,font=("aerial",16,"bold"),textvariable=pizza6,bd=10,insertwidth=4,bg="orange",justify="right")
txt3.grid(row=7,column=4)
txt4=Entry(f1,font=("aerial",16,"bold"),textvariable=pizza7,bd=10,insertwidth=4,bg="orange",justify="right")
txt4.grid(row=8,column=4)
txt5=Entry(f1,font=("aerial",16,"bold"),textvariable=pizza8,bd=10,insertwidth=4,bg="orange",justify="right")
txt5.grid(row=9,column=4)

###########################################################
lblpizza1=Label(f1,font=('aerial',16,'bold'),text="SMALL PIZZA",bd=10)
lblpizza1.grid(row=5,column=0)
txtpizza1=Entry(f1,font=("aerial",16,"bold"),textvariable=pizza1,bd=10,insertwidth=4,bg="orange",justify="right")
txtpizza1.grid(row=5,column=1)
lblpizza2=Label(f1,font=('aerial',16,'bold'),text="MEDIUM PIZZA",bd=10)
lblpizza2.grid(row=6,column=0)
txtpizza2=Entry(f1,font=("aerial",16,"bold"),textvariable=pizza2,bd=10,insertwidth=4,bg="orange",justify="right")
txtpizza2.grid(row=6,column=1)

lblpizza3=Label(f1,font=('aerial',16,'bold'),text="LARGE PIZZA",bd=10)
lblpizza3.grid(row=7,column=0)
txtpizza3=Entry(f1,font=("aerial",16,"bold"),textvariable=pizza3,bd=10,insertwidth=4,bg="orange",justify="right")
txtpizza3.grid(row=7,column=1)
############################################
lbltax=Label(f1,font=('aerial',16,'bold'),text="TAX RS",bd=10)
lbltax.grid(row=0,column=3)
txttax=Entry(f1,font=("aerial",16,"bold"),textvariable=taxcharges,bd=10,insertwidth=4,bg="orange",justify="right")
txttax.grid(row=0,column=4)
fries.set("0")
fries1.set("0")
pizza1.set("0")
pizza2.set("0")
pizza3.set("0")
pizza4.set("0")
pizza5.set("0")
pizza6.set("0")
pizza7.set("0")
pizza8.set("0")
drink.set("0")
drink1.set("0")

lblservicecharge=Label(f1,font=('aerial',16,'bold'),text="SERVICE RS",bd=10)
lblservicecharge.grid(row=1,column=3)
txtservicecharge=Entry(f1,font=("aerial",16,"bold"),textvariable=servicecharges,bd=10,insertwidth=4,bg="orange",justify="right")
txtservicecharge.grid(row=1,column=4)

lbltotal=Label(f1,font=('aerial',16,'bold'),text="TOTAL BILL RS",bd=10)
lbltotal.grid(row=2,column=3)
txttotal=Entry(f1,font=("aerial",16,"bold"),textvariable=totalbill,bd=10,insertwidth=4,bg="orange",justify="right")
txttotal.grid(row=2,column=4)
##############################################################################################################
submitbtn=Button(f1,font=('aerial',14,'bold'),text="submit",command=save,bd=10,bg="green")
submitbtn.place(x=274,y=400)

#############################################################
reset=Button(f1,font=('aerial',14,'bold'),bg="grey",text="reset",command=reset,bd=10).place(x=20,y=400)
total=Button(f1,font=('aerial',14,'bold'),bg="orange",text=" total",command=Ref,bd=10).place(x=188,y=400)
exit=Button(f1,font=('aerial',14,'bold'),bg="red",text=" exit ",command=exit,bd=10).place(x=108,y=400)
w.mainloop()
